#!/bin/bash
# ============================================================
# Script 5: Open Source Manifesto Generator
# Author: Rudrakshya Pani | Registration: 24BCY10121
# Course: Open Source Software | Chosen Software: Linux Kernel
# Description: Interactively asks the user three questions,
#              composes a personalised open-source philosophy
#              statement, and saves it to a .txt file.
# ============================================================

# --- Alias concept demonstrated via comments ---
# In a real shell session, you might define:
#   alias today='date +%d %B %Y'
#   alias greet='echo Hello, $USER'
# Aliases are shorthand commands defined for convenience.
# They are session-specific and stored in ~/.bashrc or ~/.bash_aliases.
# Below, we use the 'date' command directly (what an alias would wrap).

# --- Display intro banner ---
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          OPEN SOURCE MANIFESTO GENERATOR                    ║"
echo "║       Open Source Audit — Linux Kernel Edition              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  This tool generates a personalised open-source philosophy"
echo "  statement based on your answers. Be honest and thoughtful."
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""

# --- Interactive user input using 'read' ---
# -p flag displays a prompt inline before reading input

# Question 1: An open-source tool they use every day
read -p "  Q1. Name one open-source tool you use every day: " TOOL

# Validate: ensure the user actually typed something
while [ -z "$TOOL" ]; do
    echo "  Please enter a tool name (e.g., Firefox, Git, Linux, VLC)."
    read -p "  Q1. Name one open-source tool you use every day: " TOOL
done

echo ""

# Question 2: What 'freedom' means to them in one word
read -p "  Q2. In one word, what does 'freedom' mean to you in software? " FREEDOM

# Validate: ensure non-empty input
while [ -z "$FREEDOM" ]; do
    echo "  Please enter a single word (e.g., control, transparency, choice)."
    read -p "  Q2. In one word, what does 'freedom' mean to you? " FREEDOM
done

echo ""

# Question 3: Something they would build and share freely
read -p "  Q3. Name one thing you would build and share freely with the world: " BUILD

# Validate: ensure non-empty input
while [ -z "$BUILD" ]; do
    echo "  Please enter something you would build (e.g., a security tool, an app)."
    read -p "  Q3. Name one thing you would build and share freely: " BUILD
done

echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""

# --- Date and output file setup ---
# date '+%d %B %Y' formats as: 01 January 2025
DATE=$(date '+%d %B %Y')

# date '+%H:%M' gives current hour and minute
TIME=$(date '+%H:%M')

# Construct output filename using current username
# String concatenation in bash: simply place variables adjacent
OUTPUT="manifesto_$(whoami).txt"

# --- Compose the manifesto using string concatenation and echo >> ---
# > creates/overwrites the file; >> appends to it

# Write the header to the file (overwrites if file exists)
echo "============================================================" > "$OUTPUT"
echo "          MY OPEN SOURCE MANIFESTO" >> "$OUTPUT"
echo "============================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  Generated by : $(whoami)" >> "$OUTPUT"
echo "  Date         : $DATE at $TIME" >> "$OUTPUT"
echo "  System       : $(uname -r) on $(hostname)" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "------------------------------------------------------------" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- Main manifesto paragraph using string concatenation ---
# Each echo >> appends a line to the output file
echo "I believe in the power of open software." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Line using $TOOL variable — tool the user mentioned
echo "Every day, I rely on $TOOL — a tool built not by a single" >> "$OUTPUT"
echo "corporation for profit, but by people who chose to share their" >> "$OUTPUT"
echo "work so that others could learn, adapt, and build further." >> "$OUTPUT"
echo "That act of sharing is not weakness. It is the foundation of" >> "$OUTPUT"
echo "how the best software in the world gets built." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Line using $FREEDOM variable — their definition of freedom
echo "To me, freedom in software means $FREEDOM." >> "$OUTPUT"
echo "The Linux Kernel, covered by the GNU General Public License v2," >> "$OUTPUT"
echo "embodies this freedom in law: you can read the source, run it" >> "$OUTPUT"
echo "for any purpose, modify it to suit your needs, and share your" >> "$OUTPUT"
echo "changes with the world. These are not privileges granted by a" >> "$OUTPUT"
echo "company — they are rights protected by the license itself." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Line using $BUILD variable — what they would build and share
echo "If I were to contribute to the open-source world, I would build" >> "$OUTPUT"
echo "$BUILD — and I would release it freely, because I understand" >> "$OUTPUT"
echo "that every tool I use today exists because someone before me" >> "$OUTPUT"
echo "made the same choice. Linus Torvalds did not have to share the" >> "$OUTPUT"
echo "Linux Kernel. He chose to. That choice changed the world." >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "Open source is not just a development model. It is a philosophy:" >> "$OUTPUT"
echo "that knowledge shared is knowledge multiplied, and that the" >> "$OUTPUT"
echo "best way to build something that lasts is to build it together," >> "$OUTPUT"
echo "in the open, for everyone." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "------------------------------------------------------------" >> "$OUTPUT"
echo "  Signed: $(whoami) | $DATE" >> "$OUTPUT"
echo "============================================================" >> "$OUTPUT"

# --- Confirm and display the saved manifesto ---
echo "  ✔ Manifesto saved to: $OUTPUT"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "  PREVIEW:"
echo "────────────────────────────────────────────────────────────────"
echo ""

# Display the file contents using cat
cat "$OUTPUT"

echo ""
echo "========================================"
echo "  Manifesto generation complete."
echo "========================================"
echo ""
